config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  
  resources :questions do
     resources :answers do 
        resources :corrections do 
            put :correct, on: :member
        end
     end
  end  

  
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
	belongs_to :user
	has_many :corrections, dependent: :destroy 
	validates :text, presence: true
	
end

app/models/correction.rb
class Correction < ActiveRecord::Base
	belongs_to :user
	belongs_to :answer
	belongs_to :question
	validates :text, presence: true
	
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :user
	has_many :answers, dependent: :destroy
	has_many :corrections, dependent: :destroy
	validates :text, presence: true
	validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :questions
  has_many :answers
  has_many :corrections
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	def create
		@answer = Answer.new(answer_params)
		@answer.user_id = current_user.id if current_user
		@answer.save
	end

	private
		def answer_params
			params.require(:answer).permit(:text,:question_id)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?# Prevent CSRF attacks by raising an exception.
  protect_from_forgery with: :exception

  def configure_permitted_parameters
  	 devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password)}
  	 devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :name) }
  	 devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :name ) }
  end

  def after_sign_up_path_for(resource)
     root_path
  end

  def after_sign_in_path_for(resource)
     root_path
  end

  def after_sign_out_path_for(resource_or_scope)
      root_path
  end

  



end

app/controllers/corrections_controller.rb
class CorrectionsController < ApplicationController

	def create
		@correction = Correction.new(correction_params)
		@correction.user_id = current_user.id if current_user
		@correction.save
	end

	def correct
		type = params[:type]
		@correction = Correction.find(params[:id])
	    if type == "correct"
	      	@correction.update(correction_update_params)
	      	redirect_to root_path
		end
	end

	private

	def correction_update_params
		params.permit(:id, :text, :question_id, :answer_id, :accept)
	end

	def correction_params
		params.require(:correction).permit(:text, :question_id, :answer_id, :accept)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@questions = Question.includes(:answers).order("created_at DESC")
		@answers = Answer.all
		@answer = Answer.new
		@question = Question.new
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	def create
		@question = Question.new
	    @question = current_user.questions.create(params[:question].permit(:title, :text))
		@question.user_id = current_user.id if current_user
		@question.save
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/corrections_helper.rb
module CorrectionsHelper
	
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.erb
 <% question = Question.find(answer.question_id) %> 
 <% if question.id == answer.question_id  %>
	 <div class="media m-t-2">
	 	  <div class="media-body">
		      	<p><%= answer.text %>
		      	<% answer.corrections.each do |correction| %>
		      		<% if correction.accept == true %>
			      			 <span class="e" id="<%= correction.id + 1000 %>"><%= correction.text %></span>
			      	<% end %>
			    <% end %>
			    - <strong><%= answer.user.name %></strong> добавлено <%= l answer.created_at, format: :long %></p>
	      </div>
	      <a  data-toggle="collapse" href="#collapseExample<%= answer.id + 1 %>" aria-expanded="false" aria-controls="collapseExample", title='Написать отзыв', data-toggle ='tooltip', data-placement = 'top'  >
                  		Предложить правку
          </a><br> <br>
          <div class="collapse" id="collapseExample<%= answer.id + 1 %>">
          		<div class="card card-block">
                		<div id="correction">
                        		<%= form_for([ question, answer, Correction.new], remote: true) do |f| %>
										<ul class="corrections" style="list-style: none;"></ul>
												<div class="form-group">
														<%= f.text_area :text, autofocus: true, cols: "40", rows: "2", class:"form-control" %>
												</div>
												<%= f.text_field :question_id, value: answer.question.id, type: "hidden"  %>
												<%= f.text_field :answer_id, value: answer.id, type: "hidden"  %>
												<%= f.submit "Предложить правку",  class: "btn btn-primary pull-left" %>
								<% end %><br>		
                        </div>
                 </div><br>
           </div><br>
           <div id="correction<%= answer.id %>" class="cor">
		   		<%= render :partial => 'corrections/correction', :collection => answer.corrections %>
           </div>
     </div>
     
<% end %>

 

app/views/answers/create.js.erb
$("ul.answers").html("")
<% if @answer.errors.any? %>
	  <% @answer.errors.full_messages.each do |message| %>
	    	$("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
	  <% end %>
<% else %>
	  $("ul.answers").append($("<li />").html("Вы дали ответ"))
	  $('#answer<%= @answer.question.id %>').html("<%=j render @answer %>");
	  
<% end %>

app/views/corrections/_correction.html.erb
<div class="media m-t-2">
		<div class="media-body">
	    		<p> 
	      			<% if correction.accept == true %>
	      		 			<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
	      		 	<% else %>
	      		 			<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
	      		 	<% end %>
	      		 	<%= correction.text %> - <strong> <%= correction.user.name %></strong> добавил <%= l correction.created_at, format: :long %>
					<% if correction.accept == true %>
							<span id="<%= correction.id %>">, принято </span> <%= l correction.created_at, format: :long %>
					<% end %>
	      		</p>
	      		<% if correction.accept == false && correction.user_id == correction.question.user_id %>
		      			<a  data-toggle="collapse" href="#collapseExample<%= correction.id + 1 %>" aria-expanded="false" aria-controls="collapseExample", title='Принять правку', data-toggle ='tooltip', data-placement = 'top'  >
	                  		Принять правку
	          			</a><br> <br>
	          			<div class="collapse" id="collapseExample<%= correction.id + 1 %>">
	                      		<div class="card card-block">
	                      				<form>
			  								<div class="form-group">
			    								<label for="text">Принять правку:</label>
			    								<input type="text" class="form-control" id="text" value="<%= correction.answer.text %> <%= correction.text %>">
			  								</div>
	  										<%= link_to "Принять правку" , correct_question_answer_correction_path(correction, type: "correct", answer_id: correction.answer.id, id: correction.id,  accept: true ), method: :put , class:"btn btn-primary pull-left"  %>
										</form>
							     </div>
	                     </div>
	                     
                <% end %>
                <script type="text/javascript">
						$("#<%= correction.id %>").hover(function(){
							$('#<%= correction.id + 1000 %>').css("background-color","#c5fde0");
      					},
						function(){
    						$('#<%= correction.id + 1000 %>').css("background-color","#FFFFFF");
 						}
      					);
				</script>
	      </div>
</div>	     

app/views/corrections/create.js.erb
$("ul.corrections").html("")
<% if @correction.errors.any? %>
	  <% @correction.errors.full_messages.each do |message| %>
	    	$("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
	  <% end %>
<% else %>
	  $("ul.corrections").append($("<li />").html("Вы сделали поправку"))
	  $('#correction<%= @correction.answer.id %>').html("<%=j render @correction %>");
<% end %>

app/views/home/index.html.erb
<% unless user_signed_in? %>
      <div class="row">
           <div class="col-md-8 col-md-offset-4">
              <h1>Тестовое задание "Датарум"</h1>
              <div class="col-md-offset-1">
                  <%= link_to 'Войти', new_user_session_path, class:"btn btn-primary" %>
                  <%= link_to 'Зарегистрироваться', new_user_registration_path, class:"btn btn-primary" %>
              </div>
            </div>
      </div>
<% else %>
      <div class="row">
         <div class="col-md-8 col-md-offset-4">
             <h1>Тестовое задание "Датарум"</h1>
             <div class="col-md-offset-2">
                  <div class="comment-button">
                    <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample", title='Написать отзыв', data-toggle ='tooltip', data-placement = 'top' >
                        Задать вопрос
                    </a><br>  
                 </div>
                  
             </div>
          </div>
          <div class="col-md-8 col-md-offset-2">
              <div class="collapse" id="collapseExample">
                      <div class="card card-block">
                             <div id="question">
                                  <%= render :partial => 'questions/form', :locals => {:question => @question} %>
                             </div> <br>
                      </div>
              </div><br>
          </div>
          <div id="com">
                <%= render :partial => 'questions/question', :collection => @questions.order("created_at DESC") %>
          </div>
      </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top " role="navigation">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-offset-1">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <div class="navbar-header">
                         <%= link_to "QuestionApp", root_path, class:"navbar-brand"%>
                    </div>
                    <ul class="nav navbar-nav" >
                        <% if user_signed_in? %>
                            <li><%= link_to 'Выйти',  destroy_user_session_path, :method => :delete %></li>
                        <% else %>
                            <li><%= link_to 'Войти', new_user_session_path %></li>
                            <li><%= link_to 'Зарегистрироваться', new_user_registration_path %></li>
                        <% end %>
                    </ul>
                </div>
           </div>
      </div>
   </div>   
</nav>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		 <% flash.each do |key, value| %>
			  <div class="alert alert-<%= key %>">
			      <a href="#" data-dismiss="alert" class="close">×</a>
			      <ul style="list-style: none;">
			      	  <li>
			        	  <%= value %>
			      	  </li>
			      </ul>
			  </div>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title>QuestionApp</title>
  		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render "layouts/header" %>
		
		 <%= render 'layouts/messages' %>
		<%= yield %>
	</body>
</html>

app/views/questions/_form.html.erb
<%= form_for([current_user.questions.build], remote: true) do |f| %>
	<ul class="questions" style="list-style: none;"></ul>
	<div class="form-group">
		<p><strong>Заголовок вопроса:</strong></p>
		<%= f.text_field :title, autofocus: true, class:"form-control" %>
	</div>
	<div class="form-group">
	    <p><strong>Подробное описание ситуации:</strong></p>
		<%= f.text_area :text, autofocus: true, cols: "40", rows: "2", class:"form-control" %>
	</div>

	<%= f.submit "Задать вопрос",  class: "btn btn-primary pull-left" %>
<% end %><br>

app/views/questions/_question.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="media" >
  			<div class="media-body">
    		    <p><h5 class="media-heading"><%= question.title %> - <%= question.user.name %> - добавлено <%= l question.created_at, format: :long %> </h5>  </p> 
   				   <p><%= question.text %>  </p> 
   				   <a  data-toggle="collapse" href="#collapseExample<%= question.id + 1 %>" aria-expanded="false" aria-controls="collapseExample", title='Написать отзыв', data-toggle ='tooltip', data-placement = 'top'  >
                  		Дать ответ
             </a><br> <br>
             <div class="collapse" id="collapseExample<%= question.id + 1 %>">
                  <div class="card card-block">
                      <div id="answer">
                          <%= form_for([question, Answer.new(question_id: question.id)], remote: true) do |f| %>
                            <ul class="answers" style="list-style: none;"></ul>
                            <div class="form-group">
                                 <%= f.text_area :text, autofocus: true, cols: "40", rows: "2", class:"form-control" %>
                            </div>
                            <%= f.text_field :question_id, value: question.id, type: "hidden"  %>
                            <%= f.submit "Дать ответ",  class: "btn btn-primary pull-left" %>  
                            
                            
                        <% end %> <br>
                      </div>
                  </div>
             </div><br> 
             <div id="answer<%= question.id %>">
                  <%= render :partial => 'answers/answer', :collection => question.answers %>
        		 </div>
   			</div>
		</div>		
	</div>
</div><br>

app/views/questions/create.js.erb
$("ul.questions").html("")
<% if @question.errors.any? %>
	  <% @question.errors.full_messages.each do |message| %>
	    	$("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
	  <% end %>
<% else %>
	  $("ul.questions").append($("<li />").html("Вы задали вопрос"))
	  $("<%= escape_javascript(render @question) %>").appendTo("#com");
	  
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>